"""
/pets
    /train
        /cats
            cat1.jpg
            cat2.jpg
            ...
        /dogs
            dog1.jpg
            dog2.jpg
            ...
    /validation
        /cats
            cat101.jpg
            cat102.jpg
            ...
        /dogs
            dog101.jpg
            dog102.jpg
            ...

"""